#!/bin/bash
git config --global alias.co checkout
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.br branch
git config --global alias.hist 'log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
git config --global alias.throw 'reset --hard HEAD'
git config --global alias.throwh 'reset --hard HEAD^'
git config --global alias.last 'log -1 HEAD'
git config --global alias.undo-commit 'reset HEAD~'
git config --global alias.sbi 'submodule init'
git config --global alias.sbu 'submodule update'
git config --global alias.sbp 'submodule foreach git pull'
git config --global alias.sbc 'submodule foreach git co master'
git config --global alias.l 'log --oneline --decorate -12 --color'
git config --global alias.ll 'log --oneline --decorate --color'
git config --global alias.lc 'log --graph --color'

# 不对0x80以上的字符进行quote，解决git status/commit时中文文件名乱码
git config --global core.quotepath false

#  push for the current branch. http://dlj.bz/ogRMHl
git config --global push.default current

# curl -sSL http://dlj.bz/MQIGwj |bash
