#!/bin/bash
git config --global alias.co checkout
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.br branch
git config --global alias.hist 'log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
git config --global alias.throw 'reset --hard HEAD'
git config --global alias.throwh 'reset --hard HEAD^'
git config --global alias.last 'log -1 HEAD'
git config --global alias.undo-commit 'reset HEAD~'
git config --global alias.sbi 'submodule init'
git config --global alias.sbu 'submodule update'
git config --global alias.sbp 'submodule foreach git pull'
git config --global alias.sbc 'submodule foreach git co master'
